<%@ Page Language="C#" AutoEventWireup="true" CodeFile="safety.aspx.cs" Inherits="safety" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:Image ID="Image1" runat="server"  Height="200px" Width="95%" ImageUrl="~/images/home_slider_1.jpg" style="margin-left: 40px" />
        
    <div style="margin-left: 40px">
    
        <p style="box-sizing: border-box; margin-top: 0px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            <asp:ImageButton ID="ImageButton1" runat="server" Height="60px" ImageUrl="~/images/Homepage.jpg" OnClick="ImageButton1_Click" Width="208px" />
        </p>
        <p style="box-sizing: border-box; margin-top: 0px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            At BestMart we are 100% committed to making sure that your experience on our site is as safe as possible.</p>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            Here you can find advice on how to stay safe while trading on BestMart</p>
        <h2 style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 24px 0px 16px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">General safety advice</h2>
        <ul style="box-sizing: border-box; padding-left: 25px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            <li style="box-sizing: border-box;">
                <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">
                    <strong style="box-sizing: border-box; font-weight: 700;">Keep things local.</strong><span>&nbsp;</span>Meet the seller in person, check the item and make sure you are satisfied with it before you make a payment.
                </p>
            </li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Exchange item and payment at the same time.</strong><span>&nbsp;</span>Buyers – don&#39;t make any payments before receiving an item. Sellers – don&#39;t send an item before receiving payment.</li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Use common sense.</strong><span>&nbsp;</span>Avoid anything that appears too good to be true, such as unrealistically low prices and promises of quick money.</li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Never give out financial information.</strong><span>&nbsp;</span>This includes bank account details, eBay/PayPal info, and any other information that could be misused.</li>
        </ul>
        <img class="stay-safe" height="99" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" srcset="https://w.tonaton-st.com/dist/img/all/help/stay-safe/warning-5fa21b80.png 1x, https://w.tonaton-st.com/dist/img/all/help/stay-safe/warning-2x-1b6c5a11.png 1.3x" style="box-sizing: border-box; border: 0px; float: right; margin: 60px 0px 30px 30px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;" width="111" /><h2 style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 24px 0px 16px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            Scams and frauds to watch out for</h2>
        <ul style="box-sizing: border-box; padding-left: 25px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Fake payment services.</strong><span>&nbsp;BestMart</span> does not offer any form of payment scheme or protection. Please report any emails claiming to offer such services. Avoid using online payment services or escrow sites unless you are 100% sure that they are genuine.</li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Fake information requests.</strong><span>&nbsp;BestMart</span> verifies first-time posters to improve security of the site. If you receive an email from us asking for any personal details, we recommend that you contact us directly via phone to communicate your details and avoid potential scams.</li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Fake fee requests.</strong><span>&nbsp;</span>Avoid anyone that ask for extra fees to buy or sell an item or service. BestMart never requests payments for its basic services, and doesn&#39;t allow items that are not located in Ghana, so import and brokerage fees should never be required.</li>
            <li style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">Requests to use money transfer services such as Western Union or MoneyGram.</strong><span>&nbsp;</span>These services are not meant for transactions between strangers and many scams are run through them. Avoid requests to use these services.</li>
        </ul>
        <h2 style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 24px 0px 16px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">BestMart&#39;s safety measures</h2>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            We work continuously to ensure you have a safe, enjoyable experience on BestMart</p>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            Our safety measures include:</p>
        <ul style="box-sizing: border-box; padding-left: 25px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            <li style="box-sizing: border-box;">Hiding your email address on ads you post to protect you from spam.</li>
            <li style="box-sizing: border-box;">Giving you the option to hide your phone number on ads you post to protect you from spam.</li>
            <li style="box-sizing: border-box;">Making constant improvements to our technology to detect and prevent suspicious or inappropriate activity behind the scenes.</li>
            <li style="box-sizing: border-box;">Tracking reports of suspicious or illegal activity to prevent offenders from using the site again.</li>
        </ul>
        <h2 style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 24px 0px 16px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Reporting a safety issue</h2>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            If you feel that you have been the victim of a scam, please report your situation to us immediately. If you have been cheated, we also recommend that you contact your local police department.</p>
        <p style="box-sizing: border-box; margin-bottom: 0px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            BestMart is committed to ensuring the privacy of its users and therefore does not share information about its users publicly. However, we are committed to the safety of our users and will cooperate with the police department should we receive any requests for information in connection with fraudulent or other criminal activity.</p>
    
    </div>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px; margin-bottom: 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <h1 class="h2" style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 0px 0px 16px 40px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Contact us</h1>
        <p style="box-sizing: border-box; margin-top: 0px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px;">
            If you did not find the answer to your question or problem, please get in touch with us using the contacts below and we will respond to your message as soon as possible</p>
        <h2 style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 24px 0px 16px 40px; font-size: 1.4286rem; line-height: 1.4; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">BestMart Helpline</h2>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px;">
            Our helpline is open on all days from 9:00 AM to 6:00 PM.</p>
        <div class="helpline" style="box-sizing: border-box; margin-top: 32px; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px;">
            <img class="pull is-island" height="72" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" srcset="https://w.tonaton-st.com/dist/img/all/help/helpline-68aaedca.png 1x, https://w.tonaton-st.com/dist/img/all/help/helpline-2x-00356ddc.png 1.3x" style="box-sizing: border-box; border: 0px; float: left; margin-right: 1rem; margin-bottom: 1rem;" width="72" /><p class="h4" style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 0px; font-size: 1.1429rem; line-height: 1.5;">
                Call us</p>
            <p class="h2" style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 0px; font-size: 1.4286rem; line-height: 1.4;">
                0302 123 456</p>
            <p class="h2" style="box-sizing: border-box; font-weight: 400; color: rgb(47, 52, 50); margin: 0px; font-size: 1.4286rem; line-height: 1.4;">
                WhatsApp: +233 24 535 9157</p>
        </div>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px; margin-bottom: 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px; margin-bottom: 0px; background-color: rgb(255, 255, 255)">

        <asp:HyperLink ID="backtohomepage" runat="server" Text="Back to homepage" NavigateUrl="~/index.html" ForeColor="#990033"></asp:HyperLink>
        </p>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin-left: 40px; margin-bottom: 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="box-sizing: border-box; color: rgb(112, 118, 118); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin-left: 480px; margin-bottom: 0px; background-color: rgb(255, 255, 255)">
        <asp:Image ID="Image2" runat="server" ImageUrl="~/images/banner.jpg" Height="79px" Width="233px" style="text-align: left" />
        </p>
    </form>
</body>
</html>
